export const BEGIN_LIST_POSTS = 'BEGIN_LIST_POSTS'
export const LIST_POSTS_SUCCESS = 'LIST_POSTS_SUCCESS'
export const LIST_POSTS_ERROR = 'LIST_POSTS_ERROR'

export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS'
export const ADD_POST_ERROR = 'ADD_POST_ERROR'

export const DELETE_POST_SUCCES = 'DELETE_POST_SUCCES'
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR'